frameworkVersion: ^2.0.0

service: serverless-github-kanban-link

# app and org for use with dashboard.serverless.com
org: jameslaviron
app: kanban-link-app

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${opt:stage, 'default'}
  region: eu-west-1
  tracing:
    apiGateway: true
    lambda: true

functions:
  update:
    handler: handler.updateKanban
    events:
      - http:
          path: webhook
          method: POST
    environment:
      CLIENT_ID: ${param:clientId}
      BASE_URL: 'https://zube.io/api/'
      API_KEY: ${self:custom.mySecret.zubeApiKey}

plugins:
  - serverless-offline
  - '@serverless/safeguards-plugin'
  - serverless-webpack

custom:
  mySecret: ${ssm:/aws/reference/secretsmanager/dev/kanban/zube~true}
  safeguards:
    - safeguard: no-secret-env-vars
      title: No secrets in lambda ENV VARs
  webpack:
    includeModules: true


